.github/workflows/ci.yml
backend/typescript/migrate.js
backend/typescript/models/entity.model.ts
backend/typescript/models/index.ts
backend/typescript/rest/userRoutes.ts
backend/typescript/services/implementations/__tests__/userService.test.ts
backend/typescript/services/implementations/authService.ts
backend/typescript/services/implementations/entityService.ts
backend/typescript/services/implementations/fileStorageService.ts
backend/typescript/services/implementations/userService.ts
backend/typescript/testUtils/testDb.ts

[Setup Github Actions](https://www.notion.so/uwblueprintexecs/Configure-Github-Actions-137c974ddb674092aa90f79f1b66b610)
* Added Github Actions for:
* Running tests
* Lint checking
* Caching dependencies
1. Check if 'Checks' has the Github action running
*

build: setup github actions ci

---

.github/workflows/lint-pr.yml

N/A
* Github Action to format the PR Title to adhere to [conventional commit formatting](https://github.com/amannn/action-semantic-pull-request)

chore: add github actions to check PR Title

---

backend/typescript/server.ts
backend/typescript/services/implementations/__tests__/userService.test.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*

chore: fix buggy import statement in server.ts

---

.github/workflows/lint-pr.yml

Triggering the action on push to main was causing an error.
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*

fix: update lint workflow

---

LICENSE
README.md
backend/typescript/package.json
frontend/package.json

* Add MIT License to repo and update descriptions for `package.json`

docs: add MIT license and update documentation

---

backend/typescript/middlewares/validators/authValidators.ts
backend/typescript/middlewares/validators/userValidators.ts
backend/typescript/models/donor.model.ts
backend/typescript/models/user.model.ts
backend/typescript/rest/authRoutes.ts
backend/typescript/rest/userRoutes.ts
backend/typescript/services/implementations/__tests__/userService.test.ts
backend/typescript/services/implementations/authService.ts
backend/typescript/services/implementations/userService.ts
backend/typescript/swagger.yml
backend/typescript/types.ts
backend/typescript/utilities/firebaseRestClient.ts
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/APIClients/EntityAPIClient.ts
frontend/src/components/auth/Logout.tsx
frontend/src/components/auth/RefreshCredentials.tsx
frontend/src/components/auth/Signup.tsx
frontend/src/components/crud/CreateForm.tsx
frontend/src/components/crud/DisplayTableContainer.tsx
frontend/src/components/crud/UpdateForm.tsx
frontend/src/components/pages/__tests__/Default.test.tsx
frontend/src/types/AuthTypes.ts

[Create User Table](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* Update existing user table with phone number
* Edit auth route and services with updated types
1. Drop the existing user table in PGAdmin
2. Run `docker-compose up --build`
3. See new users table
* See if you can hit the new endpoint to create a user

feat: user table and modified auth routes

---

backend/typescript/models/user.model.ts
backend/typescript/models/volunteer.model.ts
backend/typescript/types.ts

[Create Volunteers Table](https://www.notion.so/uwblueprintexecs/Create-Volunteers-Table-2b75f538d8ac482f9570aac631642469)
* Added a new volunteer model file 
* Used foreign key to link to user table 
* set user_id to not be nullable
1. open PG admin
2. check if there is a volunteer table present
3. use a SQL query to see if you can insert a row to the volunteer table 
- inserting a volunteer that doesn't have a matching id with the user table should fail (e.g. if you haven't inserted a user with id 5 into the user table: )
`INSERT INTO volunteers (user_id, "createdAt", "updatedAt") VALUES (5, '2021-04-30', '2021-04-30')`
- having a null user_id should fail
`INSERT INTO volunteers ("createdAt", "updatedAt") VALUES ( '2021-04-30', '2021-04-30')`
- this should succeed: 
`INSERT INTO …

feat: Create volunteer table

---

backend/typescript/rest/donorRoutes.ts

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* Fixed compilation error
1. Run `docker compose up` and it should run
*

fix: Fix backend compilation error

---

frontend/src/components/auth/Login.tsx
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/CreateAccount.tsx
frontend/src/components/auth/Signup/VerificationEmail.tsx
frontend/src/components/auth/Signup/components/MandatoryInputDescription.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/pages/Default.tsx
frontend/src/components/pages/Home/DonationProcess.tsx
frontend/src/components/pages/Home/VolunteerRoles.tsx
frontend/src/components/pages/Home/index.tsx
frontend/src/theme/components/Button.tsx
frontend/src/theme/index.tsx

[Update Design System Tokens](https://www.notion.so/uwblueprintexecs/Update-Design-System-Theming-f1c7278847494db1aae9755956abc0c6)
* Updated the `textStyles` and `colors` by following the new design system theming: 
https://user-images.githubusercontent.com/19617248/140853652-df37141f-f24d-4d3a-8e79-097bc8c0ea09.mp4
1. Run locally, verify everything compiles and colours are injected correctly.

refactor: update design system elements

---

backend/typescript/rest/donorRoutes.ts
backend/typescript/services/implementations/__tests__/donorService.test.ts
backend/typescript/services/implementations/donorService.ts
backend/typescript/services/interfaces/donorService.ts
frontend/src/APIClients/DonorAPIClient.ts

allow getting donor through an optional `userId` query: 
i.e. `/donors/?userId=2`

feat: add getDonorByUserId service

---

README.md
backend/typescript/seed.js
backend/typescript/seeders/20211114043430-seed-donations.ts
backend/typescript/umzug.ts

[Seed db](https://www.notion.so/uwblueprintexecs/Seed-Database-9741abd0307a48b8bdab2144e6c16784)
* This PR adds sample donor and donations associated to that user
1. Refer to readme changes on how to seed the database
2. Verify using Pgadmin whether data was accurately added
https://user-images.githubusercontent.com/37384882/141669529-dea5d8ff-95ba-472f-9dbe-0c732eec210d.mov
* I wasnt sure whether I should be seeding the user like this since auth_id is exposed for this test user. I already created the user using the register endpoint with the following credentials: `email`: `"test@test.org` and `password`: `"password123"`

chore: seed database with donors and schedules

---

frontend/.eslintrc.js
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/APIClients/BaseAPIClient.ts
frontend/src/APIClients/DonorAPIClient.ts
frontend/src/APIClients/EntityAPIClient.ts
frontend/src/APIClients/SchedulingAPIClient.ts
frontend/src/App.tsx
frontend/src/constants/AuthConstants.ts

* extracted bearer token constant
* change import sort eslint error to warning so FE still compiles (will get fixed during `yarn fix` regardless)

chore: change sort import from `error` to `warn`

---

frontend/src/components/common/Footer.tsx
frontend/src/components/pages/Home/DonationProcess.tsx
frontend/src/components/pages/Home/VolunteerRoles.tsx
frontend/src/components/pages/Home/index.tsx
frontend/src/theme/index.tsx

* Add in CF circle logo
* update button colours
* add in pink background to donation process
* change volunteer process colours
* minor spacing and dividers
**Note:** not too sure about what the public donor calendar view on home page should be (but mocks show it included) 
https://user-images.githubusercontent.com/19617248/144022513-bda5f1d5-4b50-4a9e-a70a-1a8230044e10.mp4

style: update mobile home layout ui

---

frontend/src/components/auth/Signup/ConfirmVerificationPage.tsx
frontend/src/components/auth/Signup/index.tsx

Just UI for desktop/mobile currently, not hooked up to anything.

feat(ui): confirm email address page 

---

frontend/src/components/auth/Signup/CreateAccount.tsx
frontend/src/components/common/Calendar/WeeklyEventItems.tsx
frontend/src/components/common/RadioImageSelectGroup.tsx
frontend/src/components/common/RadioSelectGroup.tsx
frontend/src/components/common/SchedulingProgressBar.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
frontend/src/components/pages/Scheduling/DonationInformation.tsx
frontend/src/components/pages/Scheduling/GetStarted.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/Scheduling/ThankYou.tsx
frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
frontend/src/components/pages/Scheduling/index.tsx

[Scheduling Flow - Desktop Friendly](https://www.notion.so/uwblueprintexecs/Team-Hub-5b0b225bfc09415ebcfad3030ce5fd30?p=c97a05088e0440ca860d080cc2389681)
https://user-images.githubusercontent.com/40839109/144861552-32165bcb-b9e0-4e57-8454-06d4023aafe2.mov
- also updated my account page for desktop
1. Go through scheduling flow with both mobile and desktop sizing and check that everything looks correct.
*

fix: scheduling desktop views

---

backend/typescript/rest/authRoutes.ts
backend/typescript/services/implementations/authService.ts
backend/typescript/services/interfaces/authService.ts
backend/typescript/utilities/firebaseRestClient.ts
backend/typescript/yarn.lock
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/App.tsx
frontend/src/components/auth/Action.tsx
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/VerificationEmail.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/Dashboard/index.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
frontend/src/components/pages/Scheduling/index.tsx
frontend/src/constants/Routes.ts

[Fix logout](https://www.notion.so/uwblueprintexecs/Fix-logout-92188135087f43388e3df7e0a7035d65)
The reason why the "logout" capability was not working was because the middleware check for the service, `isAuthorizedByUserId` was failing (returning false). Why? 
```typescript
const firebaseUser = await firebaseAdmin
.auth()
.getUser(decodedIdToken.uid);
``` 
the firebase user object always had its `emailVerified` property as false. This means that for some reason, the email verification link sent on sign up was not working.
It works if we change it to the default:
Somewhere along the way it got changed to `localhost:3000/login` which was why the link didn't work. This gives us: 
However, we want to have a customized page and email handler for our use case for community fridge. A …

fix: custom email handler for firebase user verification

---

backend/typescript/models/scheduling.model.ts
backend/typescript/seeders/20211114043430-seed-donations.ts
backend/typescript/services/implementations/__tests__/schedulingService.test.ts
backend/typescript/types.ts
frontend/src/components/auth/Login.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/common/RadioSelectGroup.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/Scheduling/GetStarted.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/Scheduling/types.ts
frontend/src/constants/DaysInWeek.ts
frontend/src/theme/components/Container.ts

[New Figma W22 Design Visual Enhancements 
](https://www.figma.com/file/FAiUthK6jklFWCXwvXaitd/Donor-Experience-W22?node-id=181%3A12347)
1. Add radio button to the left of the radio select groups. 
2. Change sign-in to button
3. Add login error UI

style: begin misc design updates from visual enhancements

---

.github/workflows/ci.yml
.github/workflows/lint-pr.yml

* Fix to run ci and pr lint github actions for staging branch
1.

fix: ci and pr lint github actions

---

frontend/src/App.tsx
frontend/src/components/pages/UserManagement/index.tsx
frontend/src/constants/Routes.ts

Create screen to view all donors. 
* Just followed how Chakra seems to do tables, since it's a pretty simple one without any added functionality (i.e. sort) didn't feel the need to use another library (like react-table)
1. Log in to the platform, navigate to `/user-management` 
2. Check that you see a table with all donors
3. Check search capability works

feat: create donor management table

---

frontend/src/components/pages/Scheduling/BackButton.tsx
frontend/src/components/pages/Scheduling/DonationInformation.tsx
frontend/src/components/pages/Scheduling/GetStarted.tsx
frontend/src/components/pages/Scheduling/NextButton.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
frontend/src/components/pages/Scheduling/types.ts
frontend/src/theme/components/Button.ts

Hot fix for frequency input being passed incorrectly in formvalues

fix: scheduling frequency input in formvalue

---

backend/typescript/package.json
backend/typescript/rest/schedulingRoutes.ts
backend/typescript/services/implementations/__tests__/schedulingService.test.ts
backend/typescript/services/implementations/schedulingService.ts
backend/typescript/services/interfaces/schedulingService.ts
backend/typescript/types.ts
backend/typescript/yarn.lock

[Email Verification After Scheduling a Donation](https://www.notion.so/uwblueprintexecs/Email-Verification-After-Scheduling-a-Donation-c6b087683d8441e9a0a2cc397ebac56f)
* 
Create donations and see that the email reflects correctly
*

feat: email verification after scheduling donation

---

frontend/src/components/pages/Scheduling/SelectDateTime.tsx

fix: midnight donation edge case

---

frontend/src/components/pages/Scheduling/ErrorMessages.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx

fix: same day donation before current time

---

frontend/src/components/pages/Scheduling/SelectDateTime.tsx

fix: disable editing proposed end date

---

frontend/src/components/common/Calendar/CalendarInfoCard.tsx
frontend/src/components/pages/Dashboard/components/DropoffCard.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx

* Used date-fns library and specifically `differenceInDays` to validate next drop off date in `ConfirmDetails`
* Also changed ternary conditional order 
* Changed date-fns format parameter from "K" to "h" to include 1-12 in time formatting in`DropoffCard, CalendarInfoCard, ConfirmDetails`
Fixed Dropoff Date:
https://user-images.githubusercontent.com/53016529/151101680-9c66a83d-d96d-44f9-bb5a-18ba9f257b54.mov
Fixed Time Formatting:
1. Create recurring donations that only occur once. Eg a daily donation that ends on the start date, or weekly donation that ends 2 days from start day, etc. Check if there is no "Next Drop-off section" in donation details
2. Create donations that involve noon/midnight time slots -> check if it shows 12:00 instead of 00:00 (check on donation card, donation …

fix: next dropoff date + midnight time formatting

---

frontend/src/components/auth/Login.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx

Didnt create a ticket
* Change donation information api call. Since admin calendar view uses the same confirm donation details screen component, made the change so that the donor information is not fetched by the id of the authenticated user, instead from the schedule object
* Fix admin drawer and header
* redirect admin to view-donations when logged in instead of home since scheduling flow is not ready for admin
1.

fix: admin calendar card view, drawer, and header

---

frontend/src/components/pages/Home/index.tsx

fix: misaligned button in homepage

---

frontend/src/components/auth/Action.tsx
frontend/src/components/common/Footer.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/pages/Dashboard/index.tsx
frontend/src/components/pages/Home/index.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
frontend/src/components/pages/Scheduling/GetStarted.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
frontend/src/components/pages/UserManagement/index.tsx
frontend/src/components/pages/ViewDonationsPage.tsx
frontend/src/theme/components/Container.ts

* Fixed margins to be consistent throughout pages
* Header should be inline for mobile view (`Samsung Galaxy S8+ [360x740]`)
1. Check margins / page layout on Donor View
2. Check on Admin View

fix: make all margins consistent across pages

---

frontend/src/components/common/Calendar/WeeklyCalendar.tsx
frontend/src/components/pages/ViewDonations.tsx

fix: view donations css fix

---

frontend/src/components/pages/Scheduling/ConfirmDetails.tsx

fix: route to correct donation screen

---

backend/typescript/services/implementations/schedulingService.ts

fix: replace url

---

backend/typescript/rest/authRoutes.ts
frontend/src/APIClients/BaseAPIClient.ts
frontend/src/components/pages/Home/index.tsx

test: set sameSite to None to fix auth refresh

---

frontend/src/components/common/Calendar/CalendarInfoCard.tsx
frontend/src/components/common/Calendar/WeeklyCalendar.tsx
frontend/src/components/pages/Dashboard/components/DropoffCard.tsx

fix calendar styling so the widths are consistent

style: edit calendar card widths

---

backend/typescript/models/checkIn.model.ts

* add `checkIn.model.ts`
1. `docker-compose up`
2. Check pgadmin for `checkin` table and verify that fields are correct

feat: check-ins table

---

frontend/src/App.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/pages/VolunteerShifts/PendingPage.tsx
frontend/src/components/pages/VolunteerShifts/index.tsx
frontend/src/constants/Routes.ts

* Updated `App.tsx` to include route for `VolunteerShiftsPage`
* Updated `Header.tsx` to include appropriate navigation tabs for a `Volunteer` (desktop and mobile)
* `PendingPage.tsx` - displayed when volunteer status is `Pending` (page for `Approved` and `Rejected` are temporarily empty)
* Back button redirects to home
* Added `"/volunteer-shifts"` as a route
1. On volunteer account, check `Volunteer Shifts` tab for `Pending`, `Approved` and `Rejected` statuses (update values via Postman)
2. Check on mobile & desktop

feat: Add pending page for volunteers

---

backend/typescript/rest/authRoutes.ts
backend/typescript/services/implementations/authService.ts
backend/typescript/services/interfaces/authService.ts
backend/typescript/swagger.yml
backend/typescript/utilities/firebaseRestClient.ts
frontend/package.json
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/yarn.lock

Removing moment from FE since it's deprecated (https://momentjs.com/docs/#/-project-status/)
Removing unused google oauth functions

chore: remove unused moment deps

---

frontend/src/components/common/GeneralErrorModal.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/pages/Home/index.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/VolunteerShifts/PendingPage.tsx
frontend/src/components/pages/VolunteerShifts/index.tsx
frontend/src/constants/DashboardConstants.ts

* Repurposing the error modal from scheduling to use as a common component
1. Create admin account, check that you can navigate to landing page via cfkw logo. Check schedule a donation will bounce away.
2. Visual checks

fix: user experience changes for client

---

backend/typescript/services/implementations/schedulingService.ts
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/VerificationEmail.tsx

- changing copy to notify user to check junk
- add drawer logo to s3 and use that in our email content
- remove trailing and leading whitespace in email address entry 
1. Sign up to see updated copy
2. Create donation to see if the email has the drawer logo
3. try adding space in email address and it should not let you

fix: miscellaneous bugs from feedback form

---

frontend/src/components/auth/Login.tsx
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/AccountType.tsx
frontend/src/components/auth/Signup/CreateAccount.tsx
frontend/src/components/auth/Signup/FailedModal.tsx
frontend/src/components/auth/Signup/TermsConditions.tsx
frontend/src/components/auth/Signup/index.tsx
frontend/src/components/auth/Signup/types.ts
frontend/src/components/common/Header.tsx
frontend/src/components/common/HeaderLabel.tsx
frontend/src/components/common/RadioSelectGroup.tsx

* Added a new step to the signup flow for users to choose `Donor/Volunteer` account type
* Remove `business name` for volunteers
* Make `phone number` not mandatory for volunteers
* Added a mandatory terms and conditions step for volunteers
* Made UI changes to match Figma designs
1. Go through sign up flow as volunteer - ensure correct fields are shown
2. Go through sign up flow as donor - should be same as before
3. Check mobile and desktop view
https://user-images.githubusercontent.com/69697180/155259057-1a54f035-931c-4191-a0bc-0725cd552e8d.mov
https://user-images.githubusercontent.com/69697180/155259192-e3290214-8393-4a7e-a71b-7cdf936bda1f.mov

feat: Add volunteer to sign up flow

---

backend/typescript/middlewares/validators/checkInValidators.ts
backend/typescript/rest/checkInRoutes.ts
backend/typescript/server.ts
backend/typescript/services/implementations/__tests__/checkInService.test.ts
backend/typescript/services/implementations/checkInService.ts
backend/typescript/services/implementations/schedulingService.ts
backend/typescript/services/interfaces/checkInService.ts
backend/typescript/testUtils/checkInService.ts
backend/typescript/types.ts
backend/typescript/utilities/servicesUtils.ts

The service for the check in model was created along with API endpoints for create (POST) and update (PUT). Check in validators and routes (`/checkin` and `/checkin/:id`) were created.
1. Create check ins that are multi-day as well as single day via Postman. For example: 
2. Update check ins by assigning them volunteers via `volunteerID`, changing the admin status via `isAdmin`, and changing the notes via `notes`. For example:

feat: create and update check in endpoints

---

frontend/src/App.tsx
frontend/src/components/auth/Login.tsx
frontend/src/constants/AuthConstants.ts
frontend/src/contexts/VolunteerContext.ts
frontend/src/contexts/VolunteerContextDispatcher.ts
frontend/src/reducers/VolunteerContextReducer.ts
frontend/src/types/VolunteerTypes.ts

* Based on starter code's use of useReducer, useContext pattern.
* Created a local storage item for volunteerId and status.
1. Insert this into your home index page
```  
const { volunteerId, volunteerStatus } = React.useContext(VolunteerContext);
console.log(volunteerId, volunteerStatus)
```
2. Log in as a volunteer and check you have the correct id and status displayed.
3. Go into pgadmin and feel free to change these values to see if they update
4. Do the same for donor but the console.log values should be null

feat: create volunteer context

---

frontend/src/APIClients/BaseAPIClient.ts
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/ReturnToLoginModal.tsx
frontend/src/components/auth/Signup/TermsConditions.tsx
frontend/src/components/pages/UserManagement/index.tsx
frontend/src/components/pages/VolunteerDashboard/ShiftCard.tsx
frontend/src/components/pages/VolunteerDashboard/ShiftsPage.tsx
frontend/src/components/pages/VolunteerDashboard/index.tsx
frontend/src/constants/AuthConstants.ts

Auto-logging out the user after 1 hour when the access token expires.

feat: auto logout user when session expires

---

frontend/src/APIClients/BaseAPIClient.ts

🍒  Cherry pick of https://github.com/uwblueprint/community-fridge-kw/pull/192/commits/9dce35aaebc10ef2c551bda75bf972ff5460cfc5 for auto-logout in production.

feat: auto logout when token expires

---

frontend/src/components/auth/Signup/CreateAccount.tsx

* Removed donor check for mandatory phone number field in `CreateAccount.tsx`
1. Go through flow to create a new volunteer account
2. Upon signing up, phone number field should be required and highlighted as error if blank
3. Volunteer account can be created successfully

feat: make volunteer signup phone number mandatory

---

frontend/src/App.tsx
frontend/src/components/common/FridgeCheckInDescription.tsx
frontend/src/components/common/FridgeFoodRescueDescription.tsx
frontend/src/components/pages/AdminDashboard/EditCheckInDescriptionPage.tsx
frontend/src/components/pages/AdminDashboard/EditCheckInOrFoodRescue.tsx
frontend/src/components/pages/AdminDashboard/EditCheckInOrFoodRescueDescription.tsx
frontend/src/components/pages/AdminDashboard/EditFoodRescueDescriptionPage.tsx
frontend/src/constants/Routes.ts

* Added routes for edit check in description and edit food rescue description pages
* Implemented a page allowing users to edit description/url of check ins or donations
* `EditCheckInOrFoodRescue.tsx` component is used for both of these and the use case is differentiated by `isCheckInView`
* Save changes will return to the corresponding view (check in/donation) page with the new description/url (`updateContent` endpoint used)
* Clicking on the close button will return to the corresponding view with no updates
* Updated `FridgeFoodRescueDescription.tsx` and `FridgeCheckInDescription.tsx`
* it now gets data from the content API instead of static data
* allowed edit buttons to redirect users to the corresponding edit content page
1. Use Postman to POST content to `localhost:5000/content/` …

feat: edit content pages

---

backend/typescript/services/implementations/schedulingService.ts
backend/typescript/utilities/emailUtils.ts

fix: use getAdminEmail()

---

backend/typescript/server.ts

build: Update prod CORS

---

backend/typescript/rest/authRoutes.ts
backend/typescript/services/implementations/authService.ts
backend/typescript/services/interfaces/authService.ts
backend/typescript/utilities/emailUtils.ts
frontend/src/APIClients/AuthAPIClient.ts
frontend/src/components/auth/Signup/AccountDetails.tsx
frontend/src/components/auth/Signup/TermsConditions.tsx
frontend/src/components/auth/Signup/VolunteerQuestions.tsx
frontend/src/components/auth/Signup/index.tsx
frontend/src/components/auth/Signup/types.ts

* `useForm` and `useStep` functions
* mostly added upon previous implementations and used the `go` and `next`  and saved the responses in `useForm`
1. Go through the steps in volunteer and make sure the three responses page comes after account creation and before terms of service. Feel free to play around with going prev and next to ensure the flow is not broken
2. Go through the same steps in donor and ensure that the three responses page cannot be seen
3. Check if the email is sent correctly when there is a volunteer and signup flow follows intended figma designs.
Currently, the ui for one of the questions looks like this but not sure what the best way for css would be to also not break anything else. any suggestions?

feat: three questions to volunteer signup flow

---

backend/typescript/rest/healthRouter.ts
backend/typescript/server.ts

feat: add health endpoint

---

frontend/src/components/common/Card/index.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
frontend/src/components/pages/AdminDashboard/components/CheckInInfoCard.tsx
frontend/src/components/pages/Dashboard/components/DropoffCard.tsx
frontend/src/components/pages/FridgeManagement/FridgeCheckIns/DeleteCheckIns.tsx
frontend/src/components/pages/FridgeManagement/FridgeCheckIns/index.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx

Styling fixes for admin view scheduled donations and checkins from @aamyli.
- remove the coloured tag at top of View Details page 
- remove Edit from admin view details
- remove “Recurring Donation” from “Daily Recurring Donation” on cards (+ weekly,monthly..)
- missing toasts when delete shift
- checkin card heights need to be reduced
-  font size 14 for “Volunteer Assigned”, “Phone Number”, “Email Address” 
- create new shifts - missing X button
- Remove back button on account mgmt page
https://user-images.githubusercontent.com/19617248/163729104-4d5c18ce-9cfc-4d6a-9c88-11f546df4cd0.mp4
1. Most of these changes are visual, only functional ones are:
i) Delete checkin card from menu button shows toast
ii) x leads back to `admin/view-checkins` for delete checkin page and create checkin …

style: admin fridge checkin and scheduled donation design fixes

---

frontend/src/components/pages/Dashboard/index.tsx
frontend/src/components/pages/Home/index.tsx
frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
frontend/src/components/pages/Scheduling/DonationInformation.tsx
frontend/src/components/pages/Scheduling/GetStarted.tsx
frontend/src/components/pages/Scheduling/NextButton.tsx
frontend/src/components/pages/Scheduling/SaveChangesButton.tsx
frontend/src/components/pages/Scheduling/SelectDateTime.tsx
frontend/src/components/pages/Scheduling/ThankYou.tsx
frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
frontend/src/components/pages/VolunteerDashboard/ShiftCard.tsx
frontend/src/components/pages/VolunteerDashboard/ShiftsPage.tsx

* went through list of fixes to make in ticket
* added padding, changed width to full width for some mobile buttons, resize buttons (images in ticket)
1. check that all front end fixes work and match figma design

fix: button UI changes

---

frontend/src/components/auth/Signup/CreateAccount.tsx
frontend/src/components/auth/Signup/TermsConditions.tsx
frontend/src/components/pages/Home/VolunteerRoles.tsx
frontend/src/components/pages/VolunteerScheduling/ConfirmShiftDetails.tsx

* Text edits mostly. Some chakra style changes?
1. Go through the ticket and ensure the UI is correct for each bulletpoint
- http://localhost:3000/ (home) has the oxford comma under assist with food rescue
- http://localhost:3000/signup (sign up flow) has correct text and my account bolded
- tbd (terms of service) - waiting for clarification
- http://localhost:3000/volunteer-shifts (volunteer shifts) signing up shift as volunteer has correct wording

fix: requested client copy changes

---

frontend/src/components/common/FridgeCheckInDescription.tsx
frontend/src/components/common/FridgeFoodRescueDescription.tsx
frontend/src/components/pages/Account.tsx
frontend/src/components/pages/AdminDashboard/EditCheckInOrFoodRescueDescription.tsx
frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
frontend/src/components/pages/Dashboard/index.tsx
frontend/src/components/pages/Home/DonationProcess.tsx
frontend/src/theme/components/Button.ts

* Please see notion ticket for the 8 changes made in for this ticket
1. Go to related page for each change and verify that it is as asked for
**TO DO:**
* fix the lack of padding in this button
* make `Edit` inline for mobile for check-in/food rescue description

fix: misc styling changes

---

frontend/src/components/pages/Home/index.tsx

Add return on authenticated user routing for CTA buttons so error toast doesn't show up when user isn't logged in.

fix: home page volunteer and donor CTA button routing

---

backend/typescript/services/implementations/cronService.ts
frontend/src/components/pages/Dashboard/components/DropoffCard.tsx
frontend/src/components/pages/VolunteerDashboard/ShiftCard.tsx

fix: add line to reminder email copy for donors
