- docker-compose.yml
[Ticket Name](https://www.notion.so/uwblueprintexecs/Integrate-PGAdmin-TablePlus-0de6f3e6a148403e9c119b5a9da216f1)
* Added pgAdmin as a service
* For a detailed guide to set it up: [Link](https://www.notion.so/uwblueprintexecs/Guide-to-setting-up-pgAdmin-c94ec1d8be07453c9bdac90b47598076)
1. Check if pgAdmin runs locally
*
> feat: added pgadmin service

- .github/workflows/ci.yml
- backend/typescript/services/implementations/__tests__/schedulingService.test.ts
- docker-compose.ci.yml
[Fixing CI tests](https://www.notion.so/uwblueprintexecs/Fix-CI-to-run-test-db-58387cae4a9c413eb280ba1b61593f02)
> fix: backend tests

- frontend/src/APIClients/SchedulingAPIClient.ts
- frontend/src/types/SchedulingTypes.ts
[Scheduling API Client](https://www.notion.so/uwblueprintexecs/Scheduling-API-Client-d020ded90e68410eb6360fe86d93ffcc)
* Creating API clients for scheduling endpoints
1. Create dummy user
* POST to `auth/register`
sample body: `{
"firstName": "Test",
"lastName": "User",
"role": "Donor",
"email": "test@email.com",
"phoneNumber":"8888888888",
"password": "123456",
"businessName": "Test Business"
}`
* login at `http://localhost:3000/login`
2. Create dummy button with `onClick` function that triggers the following api clients:
* `SchedulingAPIClient.createSchedule`
* `SchedulingAPIClient.getSchedules`
* `SchedulingAPIClient.getScheduleById`
* `SchedulingAPIClient.updateSchedule`
* `SchedulingAPIClient.deleteSchedule`
Make sure requests are successful!
> feat: Scheduling API Clients

- backend/typescript/services/implementations/donorService.ts
- backend/typescript/yarn.lock
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/DonorAPIClient.ts
- frontend/src/components/auth/Signup/AccountDetails.tsx
- frontend/src/types/DonorTypes.ts
[Donor API Clients](https://www.notion.so/uwblueprintexecs/Donor-API-Clients-e87b689e9abd47d68f232e301778be8b)
* Added in FE clients for donor CRUD operations
1. Try calling any of the client functions on a FE page and log to see if successful
* If all client functions work
> feat: add donor API clients 

- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/middlewares/validators/donorValidator.ts
Before, not having `businessName` in `auth/register` endpoint with donor role ended up creating a user but not donor because `businessName` is a mandatory field. Change in `authAPIValidator` fixes that. Also made `facebookLink` and `instagramLink` optional.
1. Send post request to `auth/register` endpoint without businessName and request would not go through.
2. Send put request to `donor:id` endpoint without facebookLink and instagramLink and request should go through.
> fix: update validators

- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/donorRoutes.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/rest/schedulingRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/rest/volunteerRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/donorService.ts
- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/implementations/entityService.ts
- backend/typescript/services/implementations/fileStorageService.ts
- backend/typescript/services/implementations/schedulingService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/services/implementations/volunteerService.ts
- backend/typescript/utilities/errorMessageUtil.ts
* Even though `docker compose up` did not give me issues, but on vscode all the errors were underlined in red and throwing errors. This pr fixes that. I used https://github.com/uwblueprint/ccbc/pull/17 as a guide.
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#unknown-on-catch. This also explains more on why we need unknown for error type
1. Make sure I didnt break anything, so run `docker compose up` and then test some endpoints to make sure everything is working fine.
*
> fix: Fix error types

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup/AccountDetails.tsx
- frontend/src/components/auth/Signup/index.tsx
- frontend/src/components/auth/Signup/types.ts
- frontend/src/types/AuthTypes.ts
Closes: 
[Add businessName to sign up flow](https://www.notion.so/uwblueprintexecs/Fix-Registering-a-User-dd7a2800b1724e5282be338f26d2f19d)
[Hide Password input](https://www.notion.so/uwblueprintexecs/Hide-Password-Field-in-Authentication-ce74bd4e373740b98a7491cc842b9bad)
**To verify:**
If adding all inputs in the signup flow returns success.
> fix: hide password input field and add `businessName` to signup flow

- frontend/src/components/pages/Home/DonationProcess.tsx
- frontend/src/components/pages/Home/VolunteerRoles.tsx
Update landing page copy with correct wording (remove filler text)
> fix: update landing page copy

- docker-compose.yml
- frontend/src/components/common/WeeklyCalendar.tsx
- frontend/src/components/common/WeeklyEventItemPopUp.tsx
- frontend/src/components/common/WeeklyEventItems.tsx
- frontend/src/components/pages/AdminCalendar.tsx
- frontend/src/components/pages/ViewDonations.tsx
- frontend/src/constants/DaysInWeek.ts
- frontend/src/index.css
- frontend/src/theme/index.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*
> feat: view donation details popup

- frontend/src/components/pages/Scheduling/GetStarted.tsx
[Scheduling Flow - Update image and spacing](https://www.notion.so/uwblueprintexecs/Scheduling-flow-Update-get-started-image-and-spacing-8b1f390e86564b31baf923a7a3cd74ca)
* Updated Get Started image and made button spacing 100% width
1. Scheduling Get Started page should look like: 
*
> fix: Update scheduling get started page

- frontend/src/components/pages/Account.tsx
- frontend/src/components/pages/Home/DonationProcess.tsx
- frontend/src/components/pages/Home/index.tsx
[Homepage Missing Start Now Button](https://www.notion.so/uwblueprintexecs/Homepage-Missing-Start-Now-Button-dd1cacacf1cf4f80bf8f8caf551c2071)
[Homepage Styling
](https://www.notion.so/uwblueprintexecs/Homepage-Styling-fbd389a9c1ed44a5838e80df92262595)[My Account Page Styling](https://www.notion.so/uwblueprintexecs/My-Account-Page-Spacing-37986db6d7ac430fa7353b24b681f599)
* make buttons on home page full width w/ same padding
* navigate start now button depending on user authentication status
* fix misc padding and stylings
> style: fix homepage button and styling bugs

- backend/typescript/services/implementations/authService.ts
- frontend/src/components/common/Footer.tsx
- frontend/src/components/pages/Dashboard/components/DeleteScheduleModal.tsx
- frontend/src/components/pages/Dashboard/index.tsx
- frontend/src/components/pages/Home/index.tsx
- frontend/src/components/pages/Scheduling/GetStarted.tsx
- frontend/src/components/pages/Scheduling/ThankYou.tsx
- frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
* Still need to add new images + stacy modal change
1.
> refactor: update copy from usability test

- frontend/src/components/pages/Dashboard/components/DropoffCard.tsx
- frontend/src/components/pages/Dashboard/index.tsx
- frontend/src/components/pages/Scheduling/GetStarted.tsx
- frontend/src/components/pages/Scheduling/types.ts
- frontend/src/constants/DaysInWeek.ts
Add the updated donation dashboard changes from visual enhancements (P1). 
**Before**
**After**
https://user-images.githubusercontent.com/19617248/149683118-1dced696-182b-4957-b5b3-88878b93afcb.mp4
1. Schedule some recurring donations, with and without volunteer requirements
2. Check if it's close to designs on Figma
> fix: dashboard updates from visual enhancements

- backend/typescript/rest/schedulingRoutes.ts
- backend/typescript/services/implementations/__tests__/schedulingService.test.ts
- backend/typescript/services/implementations/schedulingService.ts
- backend/typescript/services/interfaces/schedulingService.ts
* All recurring donations have a ```recurring_donation_id``` (one-time donations have this as ```null```). If we want to delete the recurring donation, we will call upon the preexisting DELETE API endpoint but allow an optional parameter at ```DELETE scheduling/:id?recurringDonationId=1```
e.g. if the donation we are deleting has id: 63 and recurringDonationId: 1 we test the endpoint at
```scheduling/63?recurrringDonationId=1```
* I also deleted some unnecessary testing code that was repeated? Ideally I think a lot of the test constants should be in its own separate file but not sure what the general thoughts are here (mostly to avoid hundreds of lines of testing code in one file).
1. Ensure that you can delete recurring donations at the appropriate endpoint (create a recurring donation …
> feat: backend add delete recurring donations API endpoint

- frontend/src/components/pages/Dashboard/index.tsx
- frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
- frontend/src/components/pages/Scheduling/DonationInformation.tsx
- frontend/src/components/pages/Scheduling/types.ts
- frontend/src/theme/components/Button.ts
Styled the empty donation state on dashboard home page and added updated styling to donation details. Also added Delete Donation section that deletes a scheduled donation (not hooked up with popup modal though).
* [Desktop View](https://drive.google.com/file/d/1yDuGseH6Z6vhMdLm22d2fIZDalT7QfWW/view?usp=sharing)
* [Mobile View](https://drive.google.com/file/d/18DPeSazXr1AS4uvSfDGBDwBM4jWETWYK/view?usp=sharing)
1. Schedule some donations, delete them, check empty state of dashboard page.
2. Check if it's close to Figma designs
> fix: dashboard empty state and donation details updates from visual enhancements

- frontend/src/APIClients/UserAPIClient.ts
- frontend/src/components/pages/Account.tsx
* Checks `authenticatedUser.role` to dictate if user account info should be pulled from donor table or user table in database (admins are not accounted for in the donor table)
1. Login to an admin account (or create one using uwblueprint email)
2. Navigate to My Account tab
3. Page should load with account details, business name is Community Fridge KW
> fix: account page loading for admin

- frontend/src/components/auth/Action.tsx
Show a spinner when waiting for the email request instead of an incorrect falsy state.
Tested emails are still able to be verified
> fix: add spinner for email verification confirmation page

- frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
- frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
https://www.notion.so/uwblueprintexecs/Hide-old-values-after-making-edit-to-donation-09818f546bb54681b545b97d766b2565
https://www.notion.so/uwblueprintexecs/Fix-required-for-volunteerNeeded-field-06e6dbba65904bd7b0eb7a0fb1294e9a
* for hiding old values, made a quick fix, but for a more robust solution, we should update the values in backend as well (smth for later)
1.
> fix: small volunteer info screen bugs

- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/schedulingService.ts
* Hosting image in a public bucket on [Backblaze](https://www.backblaze.com/)
1. Create account and check that email verification header image is as expected
2. Schedule donation and check that donation confirmation email header image is as expected
> fix: change link to email header image

- backend/typescript/services/implementations/schedulingService.ts
* Fixed designs to match Figma
* Used tables instead of flexbox (not supported by some email providers like Gmail)
1. Schedule a donation, with volunteer and pickup needed + additional notes
2. Schedule a donation without volunteer needed - newly added to indicate `no volunteer/pickup needed`
3. Check confirmation email on Desktop and mobile
4. Make sure image is appropriate size and designs match Figma
Desktop - https://user-images.githubusercontent.com/69697180/152453462-e8c0c4ed-100b-4e8f-adea-520efe292d7f.mov
Mobile - https://user-images.githubusercontent.com/69697180/152452566-e2099158-be5c-4bae-ae34-84ee3839786a.MP4
Updated to emphasize volunteer time -
> fix: style email to match figma

- frontend/src/components/common/RadioImageSelectGroup.tsx
- frontend/src/components/common/RadioSelectGroup.tsx
* Fixed radio buttons so that you can click on the circle
1. Click on the circle of the radio buttons (for normal radio buttons + radio buttons w/ image for `Donation Size`)
2. Test on desktop and mobile
https://user-images.githubusercontent.com/69697180/153078635-8a0d1511-180c-4240-8edb-0361a224da8b.mov
> fix: make radio button circles clickable

- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/middlewares/validators/volunteerValidator.ts
- backend/typescript/models/volunteer.model.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/volunteerRoutes.ts
- backend/typescript/services/implementations/__tests__/volunteerService.test.ts
- backend/typescript/services/implementations/volunteerService.ts
- backend/typescript/services/interfaces/volunteerService.ts
- backend/typescript/testUtils/volunteerService.ts
- backend/typescript/types.ts
- frontend/src/APIClients/VolunteerAPIClient.ts
- frontend/src/types/AuthTypes.ts
- frontend/src/types/VolunteerTypes.ts
* Create a `VolunteerAPIClient` file that calls all the functions in `volunteerService.ts` 
* Add Volunteer types on FE with `VolunteerStatus` enum
1. We tested through the ```Dashboard``` page on frontend using the ```useEffect``` portion of the code. Here might be some helpful code to test:
```
const getAllVolunteers = async () => {
await VolunteerAPIClient.deleteVolunteerById("3");
// await VolunteerAPIClient.updateVolunteerByUserId("6",
// {
//   status: Status.APPROVED
// });
const volunteer = await VolunteerAPIClient.getAllVolunteers();
console.log(volunteer);
};
```
2. Run through all the possible varieties under volunteering API client: ```getAllVolunteers```, ```getVolunteerById```, ```getVolunteerByUserId```, ```updateVolunteerById```, ```updateVolunteerByUserId```, …
> feat: volunteer api client

- backend/typescript/services/implementations/__tests__/schedulingService.test.ts
- backend/typescript/services/implementations/schedulingService.ts
Only upcoming donations are being shown
1.
> fix: only show upcoming donations in donor dashboard

- backend/typescript/services/implementations/schedulingService.ts
- backend/typescript/utilities/emailUtils.ts
Only use cfkw admin email when it's the production environment. Avoid spam for local and staging testing.
> fix: only use cfkw admin email in production environment

- backend/typescript/.eslintrc.js
- backend/typescript/Dockerfile
- backend/typescript/middlewares/validators/checkInValidators.ts
- backend/typescript/middlewares/validators/volunteerValidator.ts
- backend/typescript/package.json
- backend/typescript/services/implementations/__tests__/contentService.test.ts
- backend/typescript/yarn.lock
- frontend/.eslintrc.js
- frontend/Dockerfile
- frontend/package.json
- frontend/src/components/auth/Action.tsx
- frontend/src/components/auth/Signup/index.tsx
- frontend/src/components/auth/utilities/index.ts
- frontend/src/components/common/RadioSelectGroup.tsx
- frontend/src/components/pages/Scheduling/CancelEditsButton.tsx
- frontend/yarn.lock
Add back eslint rule for removing unused imports, will remove when the standard `yarn fix` is run at linting.
Set it to a warning so it compiles when in the middle of development.
> chore: add eslint rule to remove unused imports

- backend/typescript/Dockerfile
- backend/typescript/package.json
- backend/typescript/services/implementations/__tests__/schedulingService.test.ts
- backend/typescript/services/implementations/cronService.ts
- backend/typescript/services/implementations/emailService.ts
- frontend/Dockerfile
- frontend/package.json
- frontend/yarn.lock
* Wrapped the `checkReminders` function into a try catch temporarily to fix the CORS errors on staging (for testing) 
* Reverted the docker image node version changes (which were originally changed for compatability in https://github.com/uwblueprint/community-fridge-kw/pull/173 for `eslint-unused-imports`) but instead using an older version of that package
1. `docker system prune -a` to delete volume, image, container
2. Run a completely fresh build of docker and check everything is fine
> chore(build): staging and docker environment fixes 

- frontend/src/components/common/Footer.tsx
Making the text clickable and not just the icons in the **Contact Us** section
> fix: make entire social media link clickable

- frontend/src/components/auth/Login.tsx
- frontend/src/components/common/Calendar/Calendar.tsx
- frontend/src/components/pages/Account.tsx
- frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
- frontend/src/components/pages/AdminDashboard/components/CheckInInfoCard.tsx
- frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
Previously, when we deleted check-ins, since the delete function was called inside of the `CheckInInfoCard` itself, the UI for the page would still display it since the parent compoennt `ViewDonationsAndCheckIns` wasn't re-rendered.
This lifts our function to the top and passed down as a handler so that we see it deleted visually.
I know we're kind of passing it multiple times down the component tree but since it's a function it's just the reference and it's only twice so it should be fine, unnecessary abstraction doesn't seem necessary here.
1. Create checkins
2. Sign in as admin navigate to view checkins
3. try deleting a checkin
> fix: handle delete for checkin at top level of component

- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/cronService.ts
- backend/typescript/services/implementations/schedulingService.ts
- backend/typescript/utilities/emailUtils.ts
extract email header and footer
also added email + socials to footer 
* moved header and footer to emailUtils file 
1. make sure emails still show up properly
> refactor: extract email header and footer

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
* implemented `sendAdminVolunteerSignUpEmail` and call it in `/register` auth route
1. Replace line 316 in `sendAdminVolunteerSignUpEmail` in `authService.ts` with and email to use for testing that will receive the new volunteer sign up email
2. Create a volunteer account
3. Check that the email received is aligned with design
> feat: send admin email on volunteer sign up

- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/PrivateRoute.tsx
- frontend/src/components/pages/Scheduling/ConfirmDetails.tsx
1. Add `volunteerOnly` and `donorOnly` route protections
2. When volunteer logs in right now it goes to donor dashboard which is incorrect, fixing that here
3. Fix the meta data on preview of the link
When volunteer is logged in:
1. Log in as volunteer and check it defaults to volunteer shift page
2. Check that you can't access donorOnly or volunteerOnly routes even as an admin
> fix: volunteer and admin default routing and add protections

- backend/typescript/rest/checkInRoutes.ts
Previously, when a checkin was getting deleted, the backend route would throw this error: 
Checkins were still being deleted successfully.
This happened because a response was already delivered to our client in the headers but the no `return` + ordering was causing an attempt at a header being set when the body is already written for the response. 
1. Delete a checkin either through postman or logged in as an admin
2. Make sure the docker logs aren't throwing this error anymore
> fix: checkin deletion backend unhandled promise error

- frontend/src/components/pages/UserManagement/index.tsx
* Display general modal to ask admin to confirm that they want to delete a user
1. Log in as admin
2. Delete a user in User Management table
3. Confirmation should appear 
4. Cancelling should not have any effect
5. Confirming the delete should delete user as required
> feat: Add confirmation modal when deleting a user

- backend/typescript/middlewares/validators/schedulingValidators.ts
- backend/typescript/middlewares/validators/util.ts
- frontend/src/components/pages/Dashboard/components/DropoffCard.tsx
- frontend/src/components/pages/FridgeManagement/FridgeCheckIns/EditCheckin.tsx
- frontend/src/components/pages/FridgeManagement/FridgeCheckIns/index.tsx
- frontend/src/components/pages/VolunteerDashboard/ShiftCard.tsx
Whenever a volunteer time was being created between midnight to 1am, it would be `00:23` for example. So 0-23 hour format. 
https://github.com/uwblueprint/community-fridge-kw/blob/419f7f72274944725f697f6627dbf8582a2b320f/frontend/src/components/pages/Scheduling/SelectDateTime.tsx#L75
But we were parsing it as `kk:mm` to display on the client side which is 1-24 hour format, causing an invalid time range error and the pages to crash in the `DropoffCard`. 
See date-fns formatting here: https://date-fns.org/v2.28.0/docs/format
We should be using `HH:mm` instead. 
- Reverted the `kk:mm` parsing 
- Changed the check in time parsing to also be `HH:mm` for consistency (since our backend refers to it as such in scheduling emails)
- Added a validator to prevent this from happening again
1. Sign in …
> fix: 24 hour date validation crash 

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/pages/UserManagement/index.tsx
- frontend/src/components/pages/UserManagement/types.ts
* `sendVolunteerApprovedEmail`  sends an info email to a volunteer when admin approves their status
* Called when admin clicks `approve`
1. Create a new volunteer with pending status
2. Sign into admin and click approve on that volunteer (at `/user-management`)
3. Check your inbox for the volunteer email
> feat: send email to volunteer when approved

- backend/typescript/services/implementations/checkInService.ts
- backend/typescript/services/interfaces/checkInService.ts
To volunteer:
To admin:
* When a volunteer cancels a check-in shift, a confirmation is sent to themselves and to admin.
1. Sign up for checkins as volunteer, cancel the shift
2. Confirm you see email
3. Confirm `communityfridgekw@uwblueprint.org` receives admin email
> feat: volunteer cancel fridge checkin emails

- backend/typescript/services/implementations/schedulingService.ts
- backend/typescript/services/interfaces/schedulingService.ts
- frontend/src/components/pages/UserManagement/index.tsx
* Send email when update to schedule is made
1. Log in as a volunteer
2. Sign up for a food rescue shift (confirmation email should be sent to admin - communityfridgekw@uwblueprint.org and volunteer)
3. Cancel the shift (cancellation email should be sent to admin - communityfridgekw@uwblueprint.org and volunteer)
Cancellation email to volunteer looks as follows:
Cancellation email to admin looks as follows:
> feat: send food rescue cancellation emails to admin and volunteer

- frontend/src/components/pages/Scheduling/SelectDateTime.tsx
- frontend/src/components/pages/UserManagement/index.tsx
* In functions where we count # of icons to show, use `toDateString` instead of `getDate`
1. Log in as a donor
2. Schedule a donation on a certain day (e.g Weekly April 20)
3. Schedule a new donation, and on the Schedule Date Time step, make sure when you are choosing the time slot, the icon on April 20 shows 1 icon as necessary, and May 20, June 20, etc are empty/don't show icons)
> fix: change icons functions to get date string

- frontend/src/components/pages/Scheduling/VolunteerInformation.tsx
Previously, when a donor edits a donation to no longer need a volunteer, we weren't setting `volunteerId` to null meaning if they required a volunteer again, the volunteer would be auto-assigned. This removes the volunteer if the donor no longer requires one.
Set `volunteerId` to `null` if the edited fields no longer has `volunteerNeeded`.
Correct payload:
1. Create a donation that requires a volunteer
2. Sign up for donation as volunteer, verify you see it in volunteer dashboard
3. Log back in as donor and remove volunteer needed on donation
4. Verify the shift is gone in the volunteer dashboard
> fix: remove volunteerId when donor edits donation to not need volunteer

- frontend/src/components/pages/AdminDashboard/components/CheckInInfoCard.tsx
- frontend/src/components/pages/VolunteerScheduling/CheckIns.tsx
Remove the volunteer assigned to a checkin when admin volunteers for it. Also filter the checkins for ones that aren't volunteers and also not admin.
> fix: set volunteerId to null when volunteering as admin

- frontend/src/components/pages/VolunteerScheduling/index.tsx
In volunteer sign up flow, the page wasnt being scrolled back to top but now it is.
1. Volunteer for a shift and make sure page scrolls to top when you proceed to the next step in the flow
> fix: page scrolling in volunteer shift sign up flow

- frontend/src/components/pages/VolunteerScheduling/ConfirmShiftDetails.tsx
Show the full start time and end time for checkin details when a volunteer signs up/view details.
1. Volunteer Dashboard > View Details for Checkins
> fix: show checkin end time for volunteer details

- frontend/src/components/pages/Scheduling/selectDateTime.css
* Update css to highlight current day in calendars
1.
> fix: add color for today in custom css sheet

- frontend/src/components/auth/Signup/CreateAccount.tsx
- frontend/src/components/common/FridgeCheckInDescription.tsx
- frontend/src/components/common/FridgeFoodRescueDescription.tsx
- frontend/src/components/pages/Account.tsx
Only show the details for future screening questions if the `role` selected is for Volunteer.
**Volunteer**
**Donor**
> fix: only have screening details for volunteers

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
Instead of sending pending email to volunteer after they verify their email, we need to send email when they register.
> fix: send volunteer pending email on signup

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/components/auth/Login.tsx
- frontend/src/components/pages/Account.tsx
- frontend/src/types/AuthTypes.ts
Add login route protection such that if a user is not verified yet in Firebase, they can't access the platform. There's three cases now:
1) `User enters wrong password for email`  🚫  Error text for "An incorrect password was entered" will appear.
2) `User enters correct password and email but are not verified` 🚫  Error text to prompt them to resend email verification will appear.
3) `User enters correct password and email and is verified` ✅  Successful login
https://user-images.githubusercontent.com/19617248/165666791-2a91d75d-83ea-4147-b115-1bbec43bd884.mp4
* Return if the email is verified from the firebase user in the login response and only log in the user if this parameter is true. 
* If it's false but the actual login was successful (credentials), prompt to resend email …
> feat: resend email verification link for unverified users on login
